In [1]:
#1
import numpy as np

array = np.random.randint(1, 101, (3, 3))
transposed_array = array.T
print("Original Array:\n", array)
print("\nTransposed Array:\n", transposed_array)

Original Array:
 [[84  4 80]
 [22 57 97]
 [81 84 15]]

Transposed Array:
 [[84 22 81]
 [ 4 57 84]
 [80 97 15]]


In [2]:
#2
import numpy as np

array_1d = np.arange(1, 11)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_2x5.reshape(5, 2)

print("1D Array:\n", array_1d)
print("\nReshaped 2x5 Array:\n", array_2x5)
print("\nReshaped 5x2 Array:\n", array_5x2)


1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [3]:
#3
array_4x4 = np.random.rand(4, 4)
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", array_4x4)
print("\n6x6 Array with Zero Border:\n", array_6x6)


Original 4x4 Array:
 [[0.5206774  0.12820108 0.47937753 0.51977023]
 [0.98616119 0.94977587 0.47089452 0.73406439]
 [0.00413677 0.17130693 0.46753539 0.48723268]
 [0.90712394 0.80125726 0.55638547 0.16909497]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5206774  0.12820108 0.47937753 0.51977023 0.        ]
 [0.         0.98616119 0.94977587 0.47089452 0.73406439 0.        ]
 [0.         0.00413677 0.17130693 0.46753539 0.48723268 0.        ]
 [0.         0.90712394 0.80125726 0.55638547 0.16909497 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
#4
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
#5
string_array = np.array(['python', 'numpy', 'pandas'])

uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)
print("Capitalize:", capitalize_array)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [6]:
#6
words_array = np.array(['hello', 'numpy', 'python'])
spaced_words_array = np.char.join(' ', words_array)

print("Original Words:", words_array)
print("Words with Spaces:", spaced_words_array)


Original Words: ['hello' 'numpy' 'python']
Words with Spaces: ['h e l l o' 'n u m p y' 'p y t h o n']


In [7]:
#7
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[5, 10, 15], [20, 25, 30]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)


Addition:
 [[15 30 45]
 [60 75 90]]

Subtraction:
 [[ 5 10 15]
 [20 25 30]]

Multiplication:
 [[  50  200  450]
 [ 800 1250 1800]]

Division:
 [[2. 2. 2.]
 [2. 2. 2.]]


In [8]:
#8
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print results
print("Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [9]:
#9
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)

# Find all prime numbers in the array
prime_numbers = random_array[np.vectorize(is_prime)(random_array)]

# Print results
print("Random Array:\n", random_array)
print("\nPrime Numbers Found:\n", prime_numbers)

Random Array:
 [901 880 835 649 777 490 682 172 380 657 404 178 849 169 731 744 530 640
 206 407 985 766 331  98 442 405  96 576 404 288 559 609 639 848 113 921
 551 787 423 460 965 574 662  26 964 359 109 689 231 336 486 703 547 177
 131 990 172 811  79 895 191 788 878  70 993 562 745 629 192 521   6 729
 556 298 348 861 520 192 457 246 121  14 963 927 245 312 717 339 801 344
 658 999  51 233 595 680 580 465  27 411]

Prime Numbers Found:
 [331 113 787 359 109 547 131 811  79 191 521 457 233]


In [10]:
#10
daily_temperatures = np.random.uniform(20, 40, 30)  # Random temperatures between 20°C and 40°C

# Reshape the array into weeks (4 weeks + 2 extra days)
weeks = daily_temperatures[:28].reshape(4, 7)  # First 4 weeks
extra_days = daily_temperatures[28:]  # Last 2 days

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Print results
print("Daily Temperatures:\n", daily_temperatures)
print("\nWeekly Averages:\n", weekly_averages)

Daily Temperatures:
 [30.48400434 26.2655743  21.52151584 25.82780317 26.01632498 25.30351423
 27.50536314 24.72229826 30.43489487 23.34854831 37.81786563 26.82514449
 23.82976739 28.98873304 31.22039753 25.95031818 33.73568152 24.88991865
 24.45426866 20.99882408 25.75136068 26.66093977 21.37359954 26.92732807
 36.35366583 28.27715511 22.36562695 37.33145106 35.70822123 35.40021856]

Weekly Averages:
 [26.13201429 27.99532171 26.71439561 28.46996662]
